apps/actas/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.acta_list, name='actas'),
    path('nueva/', views.acta_new, name='nueva_acta'),
    path('detalle/<int:pk>/', views.acta_detail, name='detalle_acta'),
    path('editar/<int:pk>/', views.acta_edit, name='editar_acta'),
    path('eliminar/<int:pk>/', views.acta_delete, name='eliminar_acta'),
]

sysctu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index/index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'), name='socios'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('actas/', include('apps.actas.urls')),
    path('socios/', include('apps.socios.urls')),
]

users/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

apps/actas/models.py
from django.db import models
import os
from datetime import datetime

"""
#eliminar todas las triples comillas para que funciones como corresponde
def path_and_rename(path):
    def wrapper(instance, filename):
        ext = filename.split('.')[-1]
        # get filename
        aux = datetime.now()
        filename = '{}.{}'.format(aux, ext)
        # return the whole path to the file
        return os.path.join(path, filename)
    return wrapper"""
    

class Acta(models.Model):
    fechaActa = models.DateField()
    numActa = models.IntegerField()
    copActa = models.FileField(null=True, blank=True, upload_to='documents/')
    #copActa = models.FileField(null=True, blank=True, upload_to=path_and_rename('documents/'))

apps/actas/forms.py
from django import forms
from .models import Acta

class ActaForm(forms.ModelForm):
    class Meta:
        model = Acta
        fields = {
            'fechaActa',
            'numActa',
            'copActa',
        }

apps/actas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ActaForm
from .models import Acta

#agregar actas
def acta_new(request):
    if request.method == 'POST':
        form = ActaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('actas')
    else:
        form =  ActaForm()
    return render(request, 'actas/reg_acta.html', {'form':form})

#listar actas
def acta_list(request):
    actas = Acta.objects.all().order_by('-fechaActa')
    contexto = {'actas': actas}       
    return render(request, 'actas/listar_actas.html',  contexto)

#seleccionar acta
def acta_detail(request, pk):
    acta = get_object_or_404(Acta, pk=pk)
    contexto = {'acta': acta}
    return render(request, 'actas/detalle_acta.html', contexto)

#editar acta
def acta_edit(request, pk):
    acta = get_object_or_404(Acta, pk=pk)
    if request.method == "POST":
        form = ActaForm(request.POST, instance=acta)
        if form.is_valid():
            acta.save()
            return redirect('detalle_acta', pk=acta.pk)
    else:
        form = ActaForm(instance=acta)
    return render(request, 'actas/reg_acta.html', {'form': form})


#borrar acta
def acta_delete(request, pk, template_name='actas/actas_confirm_delete.html'):
    acta= get_object_or_404(Acta, pk=pk)    
    if request.method=='POST':
        acta.delete()
        return redirect('listar_actas')
    return render(request, template_name, {'object':acta})

templates/actas/actas_confirm_delete.html
{% extends  'base/base.html' %}


{% block title %}Confirmar{% endblock %}

{% block content %}

{% if user.is_superuser or user.is_staff or is_operative %}

<h1>Eliminar registro de acta</h1>
<form method="post">
    {% csrf_token %}
    <div class="row justify-content-center">
        <h3> Estas seguro de eliminar a "{{ object }}" ? </h3>
    </div>
    <div class="row">
        <div class="col-8 col-md-6">
                <input type="submit" value="Eliminar" class="btn btn-outline-dark"/>
            </form>
        </div>
    </div>
   

{% else %}

<p>No tienes autorizacion para esta accion </p>

{% endif %}

{% endblock %}

templates/actas/detalle_acta.html
{% extends 'base/base.html' %}


{% block content %}
<div class="post">

  <!--  {% if user.is_superuser or user.is_staff or is_operative %}

    <div class="row">
        <div class="col-12 col-md-6">
            <a class="btn btn-outline-dark form-control" href="{% url 'editar_acta' pk=acta.id %}">Editar Acta</a>
        </div>
        <div class="col-12 col-md-6">
            <a class="btn btn-outline-dark form-control" href="{% url 'eliminar_acta' pk=acta.id %}">Eliminar</a>
        </div>
    </div>

    {% endif %}-->

    <div class="row">
        <div class="col-12">
            <a href="{% url 'editar_acta' pk=acta.id %}" class="btn">editar</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h1>Acta numero: {{ acta.numActa }}</h1>
        </div>
    </div>

    <br>

    <div class="row">
        <div class="col-12">
            <p>fecha de acta: {{ acta.fechaActa }}</p>
        </div>
    </div>
    
    <br>

    <div class="row">
        <div class="col-12">
            <p>acta: {{ acta.copActa }}</p>
            <iframe src="/meda/documents/2018-11-21_194020.203521.pdf" frameborder="0"></iframe>
            <embed src="media/{{ acta.copActa }}" style="width:900px; height:700px;" frameborder="0" type="application/pdf"></embed>
            <iframe src="https://docs.google.com/viewer?url=/media/{{ acta.copActa }}&embedded=true" width="600" height="780" style="border: none;"></iframe>
            <iframe src="/media/{{ acta.copActa }}" frameborder="0"> {{ acta.copActa }}</iframe>
        </div>
    </div>

<!--
    <h1>Object:</h1>
<object data='http://www.adventistchurchconnect.com/site/1/docs/test.pdf' 
        type='application/pdf' 
        width='100%' 
        height='300'>

<p>It appears your Web browser is not configured to display PDF files. 
No worries, just <a href='http://www.adventistchurchconnect.com/site/1/docs/test.pdf'>click here to download the PDF file.</a>
</object>
<br />
<h1>Iframe:</h1>
<iframe src="/media/{{ acta.copActa }}" width="100%" height="300">
</iframe>
<br />
<h1>Iframe (responsive - See CSS):</h1>
<div class='embed-container'><iframe src='http://www.adventistchurchconnect.com/site/1/docs/test.pdf' style='border:0'></iframe></div>
-->

</div>
{% endblock %}

templates/actas/listar_actas.html
{% extends 'base/base.html' %}

{% block title %}Actas{% endblock %}

{% block content %}

{% if user.is_superuser or user.is_staff or is_operative %}

<br>

<div class="row justify-content-center">
    <div class="col-12 col-md-8">
        <a href="{% url 'nueva_acta' %}" class="btn-outline-dark btn form-control">Ingresar nueva acta</a>
    </div>
</div>

{% endif %}

{% if actas %}

<br>

<div class="row justify-content-center">
    <div class="col-12 col-md-6">
        <table class="table table-hover">
            <tr>
                <td>Numero de acta</td>
                <td>Fecha de reunion</td>
            </tr>

            {% for acta in actas %}
            <tr>
               
                    <td> <a href="{% url 'detalle_acta' pk=acta.id %}">{{ acta.numActa }}</a></td>
                    <td>{{ acta.fechaActa }}</td>
                    <td>{{ acta.id }}</td>
                
            </tr>

            {% endfor %}
        </table>
    </div>
</div>

{% else %}

<div class="row justify-content-center">
    <div class="col-12 col-md-6">
        <h3>No se encontraron actas.</h3>
    </div>
</div>

{% endif %}


{% endblock %}

templates/actas/reg_acta.html
{% extends 'base/base.html' %}

{% block title %}Ingreso de actas{% endblock %}


{% block content %}

<div class="row justify-content-center">
        <h2>Registro de actas</h2>
</div>
<br>

{% if user.is_superuser or user.is_staff or is_operative %}

<form method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    <!--{{ form.as_p }}-->

    <div class="row justify-content-center">
        <div class="col-12 col-md-4">
            <label for="id_fechaActa">Fecha de reunión:</label>
        </div>
        <div class="col-12 col-md-4">
            {{ form.fechaActa }}
        </div>
    </div>

    <br>

    <div class="row justify-content-center">
        <div class="col-12 col-md-4">
            <label for="id_numActa">Número de acta:</label>
        </div>
        <div class="col-12 col-md-4">
            {{ form.numActa }}
        </div>
    </div>

    <br>

    <div class="row justify-content-center">
        <div class="col-12 col-md-4">
            <label for="id_copActa">Copia del acta:</label>
        </div>
        <div class="col-12 col-md-4">
            {{ form.copActa }}
        </div>
    </div>

    <br>
    <br>

    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <button type="submit" class="btn btn-block btn-outline-dark">Guardar</button>
        </div>
    </div>
</form>
{% else %}
<div class="row">
    <div class="col">
        <h2>Lo sentimos, no tienes autorización para esta seccion.</h2>
    </div>
</div>

{% endif %}


{% endblock %}